version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: web-1
    volumes:
      - .:/workspace
    ports:
      - "3000:3000"
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - cassandra
      - mysql

  cassandra:
    image: cassandra:4.0
    container_name: cassandra-1
    ports:
      - "9042:9042"

  mysql:
    image: mysql:8.0
    container_name: mysql-1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
