version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: web-1
    volumes:
      - .:/workspace
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - SCALARDB_PROPERTIES=/workspace/scalardb/database.properties
    ports:
      - "3000:3000"
    depends_on:
      - cassandra
      - mysql

  cassandra:
    image: cassandra:4.0
    container_name: cassandra-1
    environment:
      - CASSANDRA_CLUSTER_NAME=Test Cluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RAC1
      - CASSANDRA_ENDPOINT_SNITCH=SimpleSnitch
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_START_RPC=true
    ports:
      - "9042:9042"

  mysql:
    image: mysql:8.0
    container_name: "mysql-1"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
