version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/workspace
    ports:
      - "3000:3000"
    command: yarn start

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
